apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <certificate_authority_data>
    server: <kubernetes_api_server>
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-user
  name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
- name: my-user
  user:
    client-certificate-data: <client_certificate_data>
    client-key-data: <client_key_data>
