name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "Aces@redeye1" | docker login -u acesredeye --password-stdin


      - name: Build Docker image
        run: docker build -t acesredeye/wisecow:tag .

      - name: Push Docker image to Docker Hub
        run: docker push acesredeye/wisecow:tag

      - name: Deploy to Kubernetes
        run: kubectl cluster-info
